export enum Animations {
    idle = 'claw_idle',
    run = 'claw_run',
    jump = 'claw_jump',
    fall = 'claw_fall',
    damage1 = 'claw_damage1',
    damage2 = 'claw_damage2',
    swordAttack = 'claw_swordAttack',
    swordAttackJump = 'claw_swordAttackJump',
    idleOfficer = 'officer_idle',
    runOfficer = 'officer_run',
    swordAttackOfficer = 'officer_swordAttack',
    damageOfficer = 'damageOfficer',
    deathOfficer = 'deathOfficer',
    treasureRingRed = 'ringRed',
    treasureRingGreed = 'ringGreen',
    treasureRingBlue = 'ringBlue',
    treasureRingPink = 'ringPink',
    treasureCoin = 'coin',
}
