export enum FixtureType
{
    FixtureType_Min = -1,
    FixtureType_None = 0,
    // Tiles
    FixtureType_Solid,
    FixtureType_Ground,
    FixtureType_TopLadderGround,
    FixtureType_Climb,
    FixtureType_Death,
    // Sensors
    FixtureType_FootSensor,
    FixtureType_Controller,
    FixtureType_AmbientTrigger,
    FixtureType_Trigger,
    FixtureType_Projectile,
    FixtureType_Crate,
    FixtureType_PowderKeg,
    FixtureType_Pickup,
    FixtureType_Explosion,
    FixtureType_EnemyAI,
    FixtureType_EnemyAIMeleeSensor,
    FixtureType_EnemyAIDuckMeleeSensor,
    FixtureType_EnemyAIRangedSensor,
    FixtureType_EnemyAIDuckRangedSensor,
    FixtureType_EnemyAIDiveAreaSensor,
    FixtureType_DamageAura,
    FixtureType_RopeSensor,
    FixtureType_Trigger_SpawnArea,
    FixtureType_Trigger_GabrielButton,
    FixtureType_Trigger_ChaseEnemyAreaSensor,
    FixtureType_Trigger_RollAreaSensor,
    FixtureType_Max,
}
